### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by thodan36a** [andrea-daru/ESP8266_pwm_fan#1]
exit status 1
'currentFanSpeed' was not declared in this scope

**Comment by andrea-daru** [comment]
Hi @thodan36a I've updated the sketch name according to the Arduino IDE naming convention.
Maybe this was the cause of the problem.

**Comment by thodan36a** [comment]
@andrea-daru thanks you!
How to fix it? can you help me

**Comment by andrea-daru** [comment]
Just update the source code via git-pull and then compile it with Arduino IDE selecting ESP8266 Generic Board

**Comment by thodan36a** [comment]
Thank you, I successfully installed, but having trouble accessing its id: 404: Not Found

**Comment by andrea-daru** [comment]
Sorry for the delay... have you resolved? If not, can you be more specific? Thank you.

**Comment by andrea-daru** [comment]
due to inactivity
